name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:

          - name: Checkout
            uses: actions/checkout@v2
      
          - name: configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-northeast-1
      
          # Combine Terraform commands within the same step after changing directory
          - name: Terraform Commands
            run: |
              cd src
              terraform init
              terraform fmt -check
              terraform plan
      
          - name: Terraform Apply
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            run: |
              cd src
              terraform apply -auto-approve